[build]
  publish = "."

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[functions]
  directory = "netlify/functions"

# Run send-reminders every hour
[[scheduled-functions]]
  name = "send-reminders"
  cron = "0 * * * *"
